export const INITIATE_UPLOAD = 'INITIATE_UPLOAD'
export const INCREMENT_CHUNK_INDEX = 'INCREMENT_CHUNK_INDEX'
export const SET_FILE_SIZE = 'SET_FILE_SIZE'
export const ADD_UPLOADED_BYTES = 'ADD_UPLOADED_BYTES'
